version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"               # optional dashboard
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=oeugenio1999@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - "${BASE_PATH}/gluetun:/gluetun"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT=${WIREGUARD_ENDPOINT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - DNS=${DNS}
      - TZ=${TZ}
    networks:
      - edge

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8282
    volumes:
      - "${BASE_PATH}/qbittorrent:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - "${BASE_PATH}/config/lidarr:/config"
      - "${BASE_PATH}/media/music:/data/music"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/downloads/slsk/:/download/slsk"
      - "${BASE_PATH}/media/downloads/slsk/nzb:/download/slsk/nzb"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/prowlarr:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/sonarr:/config"
      - "${BASE_PATH}/media/tv-shows:/data/tvshows"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/radarr:/config"
      - "${BASE_PATH}/media/movies:/data/movies"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - "${BASE_PATH}/tdarr/server:/app/server"
      - "${BASE_PATH}/tdarr/configs:/app/configs"
      - "${BASE_PATH}/tdarr/logs:/app/logs"
      - "${BASE_PATH}/transcode:/temp"
      - "${BASE_PATH}/media:/media"
    networks:
      - web
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.silentgarden.org`)
      - traefik.http.routers.tdarr.entrypoints=web
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    volumes:
      - "${BASE_PATH}/homarr:/app/data/configs"
      - "${BASE_PATH}/homarr/icons:/app/public/icons"
      - "${BASE_PATH}/media:/data"
    networks:
      - web
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`homarr.silentgarden.org`)
      - traefik.http.routers.homarr.entrypoints=web
      - traefik.http.services.homarr.loadbalancer.server.port=7575
    environment:
      - DISABLE_UPGRADE_MODAL=true
    restart: unless-stopped

networks:
  web:
    external: true
  edge:
    external: true
    name: core_edge
