version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"               # optional dashboard
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=you@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - "${BASE_PATH}/gluetun:/gluetun"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT=${WIREGUARD_ENDPOINT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - DNS=${DNS}
      - TZ=${TZ}
    networks:
      - edge

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8282
    volumes:
      - "${BASE_PATH}/qbittorrent:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.silentgarden.org`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8282

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - "${BASE_PATH}/config/lidarr:/config"
      - "${BASE_PATH}/media/music:/data/music"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/downloads/slsk/:/download/slsk"
      - "${BASE_PATH}/media/downloads/slsk/nzb:/download/slsk/nzb"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.silentgarden.org`)
      - traefik.http.routers.lidarr.entrypoints=web
      - traefik.http.services.lidarr.loadbalancer.server.port=8686

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/prowlarr:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.silentgarden.org`)
      - traefik.http.routers.prowlarr.entrypoints=web
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/sonarr:/config"
      - "${BASE_PATH}/media/tv-shows:/data/tvshows"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.silentgarden.org`)
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/radarr:/config"
      - "${BASE_PATH}/media/movies:/data/movies"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.silentgarden.org`)
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - "${BASE_PATH}/tdarr/server:/app/server"
      - "${BASE_PATH}/tdarr/configs:/app/configs"
      - "${BASE_PATH}/tdarr/logs:/app/logs"
      - "${BASE_PATH}/transcode:/temp"
      - "${BASE_PATH}/media:/media"
    networks:
      - web
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.silentgarden.org`)
      - traefik.http.routers.tdarr.entrypoints=web
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    restart: unless-stopped

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    depends_on: [tdarr]
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - nodeID=Node-1
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - "${BASE_PATH}/tdarr/configs:/app/configs"
      - "${BASE_PATH}/tdarr/logs:/app/logs"
      - "${BASE_PATH}/transcode:/temp"
      - "${BASE_PATH}/media:/media"
    restart: unless-stopped

  tvapp2:
    container_name: tvapp2
    image: ghcr.io/thebinaryninja/tvapp2:latest
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - "${BASE_PATH}/config/tvapp2:/config"
      - "${BASE_PATH}/tvapp2/app:/usr/bin/app"
    networks:
      - web
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.tvapp2.rule=Host(`tvapp2.silentgarden.org`)
      - traefik.http.routers.tvapp2.entrypoints=web
      - traefik.http.services.tvapp2.loadbalancer.server.port=4124
    environment:
      - TZ=${TZ}
      - WEB_IP=0.0.0.0
      - WEB_PORT=4124
      - DIR_RUN=/usr/bin/app
      - STREAM_QUALITY=hd
      - FILE_M3U=playlist.m3u8
      - FILE_EPG=xmltv.xml
      - LOG_LEVEL=4
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    volumes:
      - "${BASE_PATH}/config/jellyseerr:/app/config"
    networks:
      - web
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.silentgarden.org`)
      - traefik.http.routers.jellyseerr.entrypoints=web
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NZBGET_PORT=6789
    volumes:
      - "${BASE_PATH}/config/nzbget:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/music:/data/music"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget.rule=Host(`nzbget.silentgarden.org`)
      - traefik.http.routers.nzbget.entrypoints=web
      - traefik.http.services.nzbget.loadbalancer.server.port=6789

  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - TZ=${TZ}
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - "${BASE_PATH}/config/slskd:/app"
      - "${BASE_PATH}/media/downloads/slsk/:/downloads"
      - "${BASE_PATH}/media/downloads/slsk/incomplete/:/incomplete"
    restart: unless-stopped

  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    depends_on: [gluetun, lidarr, slskd]
    network_mode: "service:gluetun"
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ}
      - SCRIPT_INTERVAL=300
    volumes:
      - "${BASE_PATH}/config/soularr:/data"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/downloads/slsk/incomplete/:/incomplete"
    restart: unless-stopped
    platform: linux/amd64

volumes:
  letsencrypt:

networks:
  web:
    driver: bridge
  edge:
    external: true
    name: core_edge
