version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "8282:8282"
      - "6881:6881"
      - "6881:6881/udp"
      - "8989:8989" # sonarr
      - "7878:7878" # radarr
      # - "8686:8686" # lidarr (commented)
      - "8787:8787"
      - "9696:9696"
      - "9191:9191"
      - "8181:8181" # headphones
      - "8080:8080"
    volumes:
      - "${BASE_PATH}/gluetun:/gluetun"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - WIREGUARD_ENDPOINT=${WIREGUARD_ENDPOINT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - DNS=${DNS}
      - TZ=${TZ}
    networks:
      - bridge
      - edge
    labels:
      # qbittorrent
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.silentgarden.org`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8282
      # sonarr
      - traefik.http.routers.sonarr.rule=Host(`sonarr.silentgarden.org`)
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      # radarr
      - traefik.http.routers.radarr.rule=Host(`radarr.silentgarden.org`)
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      # prowlarr
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.silentgarden.org`)
      - traefik.http.routers.prowlarr.entrypoints=web
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      # sabnzbd
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.silentgarden.org`)
      - traefik.http.routers.sabnzbd.entrypoints=web
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8787
      # headphones
      - traefik.http.routers.headphones.rule=Host(`headphones.silentgarden.org`)
      - traefik.http.routers.headphones.entrypoints=web
      - traefik.http.services.headphones.loadbalancer.server.port=8181
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8282
    volumes:
      - "${BASE_PATH}/qbittorrent:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/prowlarr:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/sonarr:/config"
      - "${BASE_PATH}/media/tv-shows:/data/tvshows"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    volumes:
      - "${BASE_PATH}/config/radarr:/config"
      - "${BASE_PATH}/media/movies:/data/movies"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    ports:
      - "8265:8265"   # Web UI
      - "8266:8266"   # Server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - "${BASE_PATH}/tdarr/server:/app/server"
      - "${BASE_PATH}/tdarr/configs:/app/configs"
      - "${BASE_PATH}/tdarr/logs:/app/logs"
      - "${BASE_PATH}/transcode:/temp"
      - "${BASE_PATH}/media:/media"
    networks:
      - bridge
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=Host(`tdarr.silentgarden.org`)
      - traefik.http.routers.tdarr.entrypoints=web
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    restart: unless-stopped

  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    depends_on: [tdarr]
    ports:
      - "8267:8267"   # Node port (optional to expose)
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - nodeID=Node-1
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - "${BASE_PATH}/tdarr/configs:/app/configs"
      - "${BASE_PATH}/tdarr/logs:/app/logs"
      - "${BASE_PATH}/transcode:/temp"
      - "${BASE_PATH}/media:/media"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "service:gluetun"
    depends_on: [gluetun]
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/config/sabnzbd:/config"
      - "${BASE_PATH}/media/downloads:/downloads"
      - "${BASE_PATH}/media/music:/data/music"
    restart: unless-stopped

  headphones:
    image: linuxserver/headphones
    platform: linux/amd64
    container_name: headphones
    depends_on: [gluetun]
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BASE_PATH}/config/headphones:/config"
      - "${BASE_PATH}/media/music:/music"
      - "${BASE_PATH}/media/downloads:/downloads"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - "5055:5055"
    volumes:
      - "${BASE_PATH}/config/jellyseerr:/app/config"
    networks:
      - bridge
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.silentgarden.org`)
      - traefik.http.routers.jellyseerr.entrypoints=web
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - "7575:7575"
    volumes:
      - "${BASE_PATH}/homarr:/app/data/configs"
      - "${BASE_PATH}/homarr/icons:/app/public/icons"
      - "${BASE_PATH}/media:/data"
    networks:
      - bridge
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`homarr.silentgarden.org`)
      - traefik.http.routers.homarr.entrypoints=web
      - traefik.http.services.homarr.loadbalancer.server.port=7575
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
      # - "1900:1900/udp"   # removed to avoid macOS port conflict
    volumes:
      - "${BASE_PATH}/config/jellyfin:/config"
      - "${BASE_PATH}/media/movies:/data/Movies"
      - "${BASE_PATH}/media/tv-shows:/data/TVShows"
      - "${BASE_PATH}/media/music:/data/Music"
      - "${BASE_PATH}/media/books:/data/Books"
    networks:
      - bridge
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.silentgarden.org`)
      - traefik.http.routers.jellyfin.entrypoints=web
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    restart: unless-stopped

networks:
  bridge:
    driver: bridge
  edge:
    external: true
    name: core_edge